import { LANGUAGE } from './app'

const en = {
  tagline: 'Find your next film',
  nav: {
    home: 'Home',
    searchLabel: 'Search movies and people',
    searchPlaceholder: 'Search movies or people',
    themeToLight: 'Switch to light theme',
    themeToDark: 'Switch to dark theme',
    skipToContent: 'Skip to content',
  },
  home: {
    featuredKicker: 'Latest release',
    viewFilm: 'View film',
    newReleases: 'New releases',
    newReleasesNote: 'Newest first, updated daily',
    genreFilterLabel: 'Filter by genre',
    allGenres: 'All',
    loadMore: 'Load more films',
    loadingMore: 'Loading more films…',
    endOfList: 'You have reached the end of the list.',
    emptyTitle: 'No films here yet',
    emptyBody: 'There are no recent releases in this genre. Try another one.',
    showAll: 'Show all genres',
    shownCount: (n: number) => `${n} films shown`,
  },
  movie: {
    back: 'Back',
    posterAlt: (title: string) => `Poster for ${title}`,
    released: 'Released',
    runtime: 'Runtime',
    genres: 'Genres',
    score: 'TMDB score',
    outOfTen: '/ 10',
    votes: (n: string) => `${n} votes`,
    notRated: 'Not rated yet',
    overview: 'Overview',
    noOverview: 'No synopsis available yet.',
    trailer: 'Trailer',
    playTrailer: (name: string) => `Play ${name}`,
    cast: 'Cast',
    as: 'as',
    showAllCast: (n: number) => `Show all ${n}`,
    showLessCast: 'Show fewer',
    noCast: 'No cast information yet.',
    reviews: 'Reviews',
    noReviews: 'No reviews on TMDB yet.',
    readMore: 'Read more',
    readLess: 'Show less',
    readOnTmdb: 'Read on TMDB',
    allReviews: (n: number) => `All ${n} reviews on TMDB`,
    ratedBy: (rating: number) => `${rating} / 10`,
    moreLikeThis: 'More like this',
    notFoundTitle: 'Film not found',
    notFoundBody: 'This film does not exist on TMDB, or it was removed.',
  },
  person: {
    photoAlt: (name: string) => `Photo of ${name}`,
    knownForDepartment: 'Known for',
    born: 'Born',
    died: 'Died',
    placeOfBirth: 'Place of birth',
    age: (years: number) => `age ${years}`,
    biography: 'Biography',
    noBiography: 'No biography available yet.',
    readMore: 'Read more',
    readLess: 'Show less',
    knownFor: 'Known for',
    filmography: 'Filmography',
    departmentFilterLabel: 'Filter filmography by department',
    departments: {
      Acting: 'Acting',
      Directing: 'Directing',
      Writing: 'Writing',
      Production: 'Production',
      Camera: 'Camera',
      Editing: 'Editing',
      Sound: 'Sound',
      Art: 'Art',
      'Costume & Make-Up': 'Costume & Make-Up',
      'Visual Effects': 'Visual Effects',
      Lighting: 'Lighting',
      Crew: 'Crew',
    } as Record<string, string>,
    tba: 'TBA',
    showAllCredits: (n: number) => `Show all ${n}`,
    showFewerCredits: 'Show fewer',
    noCredits: 'No film credits yet.',
    notFoundTitle: 'Person not found',
    notFoundBody: 'This person does not exist on TMDB, or the profile was removed.',
  },
  search: {
    title: 'Search',
    pageTitle: (q: string) => `Results for “${q}”`,
    inputLabel: 'Search films and people',
    placeholder: 'Try “Nolan” or “The Dog Stars”',
    promptTitle: 'Find a film or a person',
    promptBody: 'Search by title, actor or director.',
    searching: 'Searching…',
    resultsCount: (films: number, people: number) =>
      `Showing ${films} ${films === 1 ? 'film' : 'films'} and ${people} ${people === 1 ? 'person' : 'people'}`,
    people: 'People',
    films: 'Films',
    noResultsTitle: 'Nothing found',
    noResultsBody: (q: string) => `No films or people match “${q}”. Check the spelling or try fewer words.`,
    loadMore: 'Load more results',
  },
  footer: {
    attribution:
      'This product uses TMDB and the TMDB APIs but is not endorsed, certified, or otherwise approved by TMDB.',
    tmdbAlt: 'The Movie Database (TMDB)',
  },
  errors: {
    title: 'Something went wrong',
    generic: 'We could not load this right now. Please try again in a moment.',
    retry: 'Try again',
    notFoundTitle: 'Page not found',
    notFoundBody: 'The page you were looking for does not exist or has moved.',
    backHome: 'Back to home',
    missingKeyTitle: 'TMDB API key missing',
    missingKeyBody: 'Add VITE_TMDB_API_KEY to a .env.local file (see .env.example) and restart the dev server.',
  },
} as const

export type Strings = typeof en

// Add more locales here (e.g. `es`) and they are picked up from LANGUAGE.
const catalog: Record<string, Strings> = { en }

export const t: Strings = catalog[LANGUAGE.split('-')[0]] ?? en
